### ISSUE TITLE
Going back with browser back

### ISSUE THREAD

**Issue by spekulatius** [silverstripe/silverstripe-multiform#49] opened 2015-11-24 10:41 UTC
While using a multi step form and going back more than one step I would expect to always come to the logical next steps as defined. But instead I end up on the next step based on the already submitted steps. This leads to the impression that im "jumping" between the steps. Is that intentional for reasons I'm not aware of? If not I'm happy to provide a fix.

**Comment by dhensby** [comment] 2015-11-25 16:01
I imagine that this is *not* by design but also not necessarily a bug.

There probably needs to be a discussion around what the preferred behaviour is for this scenario. It should probably follow the same logic as pressing a back button on the form repeatedly

**Comment by spekulatius** [comment] 2015-11-25 20:18
Hello @dhensby 

thanks for you reply. Who do you think we should invite to this discussion?

Spek

**Comment by dhensby** [comment] 2015-11-26 00:19
@halkyon @chillu @wilr @tractorcow maybe?

**Comment by chillu** [comment] 2016-01-08 01:07
Hey Peter, it's been a while since I've used this module, but to my best knowledge this isn't by design. In order to preserve step navigation, you have to ensure that each redirect to the next step after a form submission includes a `StepID`. See `MultiForm->next()` and `MultiFormStep->getLink()` on how that holds together. You could just overwrite `getLink()` in a subclass for that, but I think this could be a good configuration option in the module.

**Comment by wilr** [comment] 2017-09-11 22:16
This should now be fixed with the explicit `StepID` being provided in the URL to go back too.

**Closed by wilr** 2017-09-11 22:16 UTC
